### ISSUE TITLE
mint not part of icrc7 standard

### ISSUE THREAD

**Issue by letmejustputthishere** [pramitgaha21/icrc7#1]
https://github.com/pramitgaha21/icrc7/blob/0ec19a636df5eb58a0038926df5d1a1087f3773e/icrc7/icrc7.did#L83

can you remove the prefix for non standard methods such as mint and burn please?

**Comment by pramitgaha21** [comment]
removed: https://github.com/pramitgaha21/icrc7/blob/main/icrc7/icrc7.did#L95
